### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by josephmiller2000** [djjorik/angular-chat#1]
What do you mean npm run dev (required mongodb)? in readme file.

How to start the chat?

**Comment by josephmiller2000** [comment]
No idea what happened.. but this error appeared while installing the chat.

**Comment by djjorik** [comment]
I guess its not issue with app, but with npm. Try to update npm like this 

> npm install npm -g || or ||  npm i -g npm@5.6.0 

or delete and re-install it. Also i'd reccomend you update your node version to the latest.

**Comment by josephmiller2000** [comment]
Alright now it works..

You asked to run mongodb before installing right? i did.

But, do we have to manually add any database information before starting the chat?

I got end up stuck in this page.
![snap_2018 04 18_21h06m45s_002_](https://user-images.githubusercontent.com/24210340/38942507-9a0de80a-434c-11e8-8e00-3fa402bcbec3.png)

**Comment by djjorik** [comment]
It seems its not working correctly, please git pull the latest version of app, i fixed it. If  you pulled and its still not working, try to go to page 'localhost:4200/auth' and there you should  register and login, but i am thinking in the latest verions of app there is no should be this issue.

**Comment by josephmiller2000** [comment]
Alright :) after fetching new git file. It works fine.

Make it mobile responsive and make the username and messages to appear and look like this

![snap_2018 04 19_23h29m22s_008_](https://user-images.githubusercontent.com/24210340/39009531-8753c864-4429-11e8-8c23-a8800cd2e6bb.png)

Username comes at the left side and the message goes below the username.

**Comment by djjorik** [comment]
closed
